---
# https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.rhel7.txt#L368

- name: Ensure lief dependencies are present
  ansible.builtin.package:
    name:
      - cmake
      - gcc
    state: present

- name: Install lief - may take a while
  ansible.builtin.pip:
    name: lief
    state: present
    version: "{{ fact_lief_version | default(omit) }}"
    extra_args: --upgrade --prefer-binary
    virtualenv: "{{ fact_python_virtualenv | default(omit) }}"
  register: pkg_result
  until: pkg_result is success

- name: Ensure LIEF is working
  ansible.builtin.command: "python3 -c 'import lief'"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  changed_when: false
  when:
    - fact_python_virtualenv is not defined or fact_python_virtualenv == None

- name: Ensure LIEF is working - virtualenv
  ansible.builtin.command: "{{ fact_python_virtualenv }}/bin/python3 -c 'import lief'"
  changed_when: false
  when:
    - fact_python_virtualenv is defined
    - fact_python_virtualenv | length > 0
