---
# tasks file for juju4.fact

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution != 'Fedora'
- name: Include for Fedora
  include_vars: "Fedora.yml"
  when: ansible_distribution == 'Fedora'

- include_tasks: mongodb-thp.yml
- include_tasks: fact.yml
