---
# tasks file for juju4.fact

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution != 'Fedora'
- name: Include for Fedora
  ansible.builtin.include_vars: "Fedora.yml"
  when: ansible_distribution == 'Fedora'

- name: Include mongodb-thp
  ansible.builtin.include_tasks: mongodb-thp.yml
  when: fact_version is regex('^3\.')
- name: Include fact
  ansible.builtin.include_tasks: fact.yml

- name: Include backup-restore
  ansible.builtin.include_tasks: backup-restore.yml
- name: Include fact-restore
  ansible.builtin.include_tasks: fact-restore.yml
  when: fact_restore_archive|string
