---
# https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/#transparent-huge-pages-thp-settings
# https://askubuntu.com/questions/597372/how-do-i-modify-sys-kernel-mm-transparent-hugepage-enabled

- name: Ensure package sysfsutils is present
  package:
    name: sysfsutils
    state: present

- name: Set transparent_hugepage
  lineinfile:
    dest: /etc/sysfs.conf
    regexp: '^kernel/mm/transparent_hugepage/enabled = .*'
    line: 'kernel/mm/transparent_hugepage/enabled = never'
