---

- name: Ensure appropriate directories for mongodb
  file:
    path: "{{ item.p }}"
    mode: "{{ item.m }}"
    owner: "{{ item.o }}"
    state: directory
  with_items:
    - { p: /tmp, m: '1777', o: root }
    - { p: /media/data/fact_wt_mongodb, m: '0744', o: "{{ fact_user }}" }
    - { p: /media/data/fact_auth_data, m: '0744', o: "{{ fact_user }}" }

- name: Ensure package mongodb service is stopped and disabled (included in fact-db)
  service:
    name: mongodb
    state: stopped
    enabled: no

- name: Ensure fact-db service is started
  service:
    name: fact-db
    state: started

- name: Mongo | create admin user
  mongodb_user:
    login_host: localhost
    login_port: 27018
    database: fact_main
    name: "{{ item.n }}"
    password: "{{ item.p }}"
    roles: "{{ item.r }}"
    state: present
  with_items:
    - { n: "{{ fact_main_config[0].v }}",
        p: "{{ fact_main_config[1].v }}",
        r:
          - role: 'dbOwner'
            db: 'admin'
          - role: 'readWriteAnyDatabase'
            db: 'admin'
          - role: 'root'
            db: 'admin'
    }

- name: Mongo | create user
  mongodb_user:
    login_user: "{{ fact_main_config[0].v }}"
    login_password: "{{ fact_main_config[1].v }}"
    login_host: localhost
    login_port: 27018
    database: fact_main
    name: "{{ item.n }}"
    password: "{{ item.p }}"
    roles: "{{ item.r }}"
    state: present
  with_items:
    - { n: "{{ fact_main_config[2].v }}",
        p: "{{ fact_main_config[3].v }}",
        r:
          - role: 'readAnyDatabase'
            db: 'admin'
    }
