---

- name: Fedora | Use systemctl for nginx restart
  ansible.builtin.lineinfile:
    dest: "{{ fact_root }}/src/install/frontend.py"
    regexp: "^    nginx_output, nginx_code = execute_shell_command_get_return_code.'sudo (.*)'.$"
    line: "    nginx_output, nginx_code = execute_shell_command_get_return_code('sudo systemctl restart nginx')"
    mode: '0644'
  when: ansible_distribution == 'Fedora'

# /var/_fact/FACT_core/src/web_interface/templates/maintenance.html
- name: Allow nobody (nginx) to traverse home
  ansible.posix.acl:
    path: "{{ fact_home }}"
    entity: nobody
    etype: user
    permissions: x

- name: Github | review nginx.conf
  ansible.builtin.replace:
    dest: "{{ fact_root }}/src/config/nginx.conf"
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    mode: '0644'
  with_items:
    - { re: '^        listen   443;', rep: '        listen   443 ssl;' }
    - { re: '^        ssl on;', rep: '        # ssl on;' }
  when: fact_nginx_shim

- name: Nginx | Ensure logs in target directory
  ansible.builtin.replace:
    dest: "{{ fact_root }}/src/config/nginx.conf"
    regexp: "access_log .* compression;"
    replace: "access_log {{ fact_logdir }}/fact_web.log compression;"
    mode: '0644'

- name: Remove user/group in nginx.conf as in systemd
  ansible.builtin.replace:
    dest: /etc/nginx/nginx.conf
    regexp: '^user (.*);'
    replace: '#user \1;'
    mode: '0640'

- name: Align pid path in nginx.conf
  ansible.builtin.replace:
    dest: /etc/nginx/nginx.conf
    regexp: '^pid .*'
    replace: 'pid /run/nginx/nginx.pid;'
    mode: '0640'

- name: Ensure /run/nginx exists
  ansible.builtin.file:
    path: /run/nginx
    state: directory
    mode: '0755'
    owner: "{% if ansible_os_family == 'RedHat' %}nginx{% else %}www-data{% endif %}"

- name: Ensure certificates and log files are accessible to www-data
  ansible.posix.acl:
    path: "{{ item.p }}"
    entity: "{% if ansible_os_family == 'RedHat' %}nginx{% else %}www-data{% endif %}"
    etype: user
    permissions: "{{ item.perm }}"
    state: present
  loop:
    # only exist after install.py
    # - { p: /etc/nginx/fact.key,
    #     perm: r
    # }
    - { p: /var/log/nginx,
        perm: rwx
    }

- name: Systemd
  block:
    - name: Ensure no conflicting pid path
      ansible.builtin.replace:
        dest: /lib/systemd/system/nginx.service
        regexp: "{{ item.re }}"
        replace: "{{ item.rep }}"
        mode: '0644'
      with_items:
        - { re: '^PIDFile=/run/nginx.pid', rep: '#PIDFile=/run/nginx.pid' }
        - { re: '--pidfile /run/nginx.pid', rep: '--pidfile /run/nginx/nginx.pid' }
        # Centos 7
        - { re: '^ExecStartPre=/usr/bin/rm -f /run/nginx.pid', rep: 'ExecStartPre=/usr/bin/rm -f /run/nginx/nginx.pid' }
      notify:
        - Reload systemd
        - Restart nginx
      register: nginx_systemd
  rescue:
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system
        state: pre
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system/nginx.service
        state: pre
    - name: Ensure no conflicting pid path (immutable)
      ansible.builtin.replace:
        dest: /lib/systemd/system/nginx.service
        regexp: '^PIDFile=/run/nginx.pid'
        replace: '#PIDFile=/run/nginx.pid'
        mode: '0644'
      notify:
        - Reload systemd
        - Restart nginx
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system
        state: post
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /lib/systemd/system/nginx.service
        state: post
