---
# https://github.com/fkie-cad/FACT_core/blob/master/src/plugins/analysis/users_and_passwords/install.sh

- name: Install users_and_passwords pip dependencies
  pip:
    name: git+https://github.com/fkie-cad/common_helper_passwords.git
    state: present

- name: Check video card for GPU acceleration
  command: lshw -c display
  changed_when: false
  register: lshw
- name: Add nvidia package
  set_fact:
    fact_users_and_passwords_pkgs:
      - "{{ fact_users_and_passwords_pkgs }}"
      - nvidia-opencl-dev
  when: "'NVIDIA' in lshw.stdout"
- name: Add AMD package
  set_fact:
    fact_users_and_passwords_pkgs:
      - "{{ fact_users_and_passwords_pkgs }}"
      - ocl-icd-opencl-dev
      - opencl-headers
  when: "'AMD' in lshw.stdout"

- name: Install users_and_passwords package dependencies
  package:
    name: "{{ fact_users_and_passwords_pkgs }}"
    state: present

- name: Check if john the ripper present
  stat:
    path: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/run/john"
  register: johnr
- block:
    - name: Ensure john directory exists
      file:
        path: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john"
        state: directory
        mode: '0755'
        owner: "{{ fact_user }}"
    - name: Download John the ripper
      get_url:
        url: https://github.com/openwall/john/archive/1.9.0-Jumbo-1.tar.gz
        dest: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john"
        checksum: "sha256:48526d9f066d7b135c60e7444e0d2473c5b1438bf8379826945a78c91a95d79b"
        mode: '0644'
    - name: Extract John archive
      unarchive:
        src: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/john-1.9.0-Jumbo-1.tar.gz"
        dest: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john"
        mode: '0755'
        remote_src: yes
        # Ansible module does not handle this well. doing symlinks.
        # extra_opts:
        #   - --strip-components 1
      become: yes
      become_user: "{{ fact_user }}"
    - name: Build John the ripper
      command: "{{ item.c }}"
      args:
        chdir: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/john-1.9.0-Jumbo-1/src"
        creates: "{{ item.t }}"
      with_items:
        - { c: ./configure --disable-openmap, t: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/john-1.9.0-Jumbo-1/src/Makefile" }
        - { c: make clean, t: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/john-1.9.0-Jumbo-1/src/xyz" }
        - { c: make -j4, t: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/john-1.9.0-Jumbo-1/run/john" }
      become: yes
      become_user: "{{ fact_user }}"
    - name: Add symlinks
      file:
        src: "{{ item.s }}"
        dest: "{{ item.d }}"
        state: link
        mode: '0755'
      with_items:
        - { s: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/john-1.9.0-Jumbo-1/src", d: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/src" }
        - { s: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/john-1.9.0-Jumbo-1/run", d: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/bin/john/run" }
      become: yes
      become_user: "{{ fact_user }}"
  when: not johnr.stat.exists

- name: Download common credentials
  get_url:
    url: https://raw.githubusercontent.com/danielmiessler/SecLists/f9c1ec678c1cae461f1dc8b654ceb6719fd03d33/Passwords/Common-Credentials/10k-most-common.txt
    dest: "{{ fact_root }}/src/plugins/analysis/users_and_passwords/internal"
    mode: '0600'
  notify:
    - users_and_passwords-update_password_list
