---
# https://github.com/fkie-cad/FACT_core/blob/master/src/plugins/analysis/oms/install.sh

- name: Install oms package dependencies
  package:
    name: "{{ fact_oms_pkgs }}"
    state: present

# FIXME: ERROR: Could not find a version that satisfies the requirement common-analysis-base-0-1 (unavailable)\nERROR: No matching distribution found for common-analysis-base-0-1 (unavailable)
- name: Install oms pip
  pip:
    name:
      - git+https://github.com/mass-project/common_analysis_base.git#egg=common_analysis_base-0.1
      - git+https://github.com/fkie-cad/common_analysis_oms.git
    state: present
    extra_args: --upgrade
  ignore_errors: true

- name: check if existing signatures db
  stat: path=/var/lib/clamav/main.cvd
  register: db
- name: check if existing daily.cld db
  stat: path=/var/lib/clamav/daily.cld
  register: db2
- name: check if existing daily.cvd db
  stat: path=/var/lib/clamav/daily.cvd
  register: db3
- block:
    - name: stop freshclam service during update
      service: name=clamav-freshclam state=stopped
    - name: ensure signatures are present before starting clamav
      command: "freshclam"
      args:
        creates: /var/lib/clamav/daily.cld
  when: not db.stat.exists or (not db2.stat.exists and not db3.stat.exists)
