---
# https://github.com/fkie-cad/FACT_core/blob/master/src/plugins/analysis/crypto_hints/install.sh
# https://github.com/Yara-Rules/rules/blob/master/crypto/crypto_signatures.yar

- name: Ensure directory exists
  file:
    path: "{{ fact_root }}/src/plugins/analysis/crypto_hints/signatures"
    state: directory
    mode: '0755'
    owner: "{{ fact_user }}"

- name: Get Crypto Yara signatures
  get_url:
    url: https://raw.githubusercontent.com/Yara-Rules/rules/master/crypto/crypto_signatures.yar
    dest: "{{ fact_root }}/src/plugins/analysis/crypto_hints/signatures/crypto_signatures.yar"
    mode: '0644'
    owner: "{{ fact_user }}"
    # checksum: ?
