---

- name: Debug | ansible_virtualization_type
  debug: var=ansible_virtualization_type
- name: Debug | ansible_service_mgr
  debug: var=ansible_service_mgr

- block:

    - name: install systemd fact-db configuration
      template:
        src: "systemd-fact-db.service.j2"
        dest: "/lib/systemd/system/fact-db.service"
        mode: '0644'
        backup: yes
      register: systemd
      ignore_errors: true
      notify:
        - reload systemd
        - "restart fact-db"

    - name: install systemd fact-backend configuration
      template:
        src: "systemd-fact-backend.service.j2"
        dest: "/lib/systemd/system/fact-backend.service"
        mode: '0644'
        backup: yes
      register: systemd
      ignore_errors: true
      notify:
        - reload systemd
        - "restart fact-backend"

    - name: install systemd fact-frontend configuration
      template:
        src: "systemd-fact-frontend.service.j2"
        dest: "/lib/systemd/system/fact-frontend.service"
        mode: '0644'
        backup: yes
      register: systemd
      ignore_errors: true
      notify:
        - reload systemd
        - "restart fact-frontend"

  # when: ansible_service_mgr == 'systemd'
  when: >
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
    (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)

- name: Flush handlers
  meta: flush_handlers

- name: enable and start fact systemd service
  service:
    name: "fact-{{ item }}"
    enabled: "{{ fact_svc_enable | default(true) }}"
    state: "{{ fact_svc_state | default('started') }}"
  with_items:
    - db
    - backend
    - frontend
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker")
        )

- name: Give 5 seconds to ensure service correctly started
  pause:
    seconds: 5
