---

- name: Debug | ansible_virtualization_type
  ansible.builtin.debug:
    var: ansible_virtualization_type
- name: Debug | ansible_service_mgr
  ansible.builtin.debug:
    var: ansible_service_mgr

- name: Minimum distribution release
  # when: ansible_service_mgr == 'systemd'
  when: >
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 16) or
    (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
  block:

    - name: Install systemd fact-db configuration
      ansible.builtin.template:
        src: "systemd-fact-db.service.j2"
        dest: "/lib/systemd/system/fact-db.service"
        mode: '0644'
        backup: yes
      register: systemd
      ignore_errors: true
      notify:
        - Reload systemd
        - "Restart fact-db"

    - name: Install systemd fact-backend configuration
      ansible.builtin.template:
        src: "systemd-fact-backend.service.j2"
        dest: "/lib/systemd/system/fact-backend.service"
        mode: '0644'
        backup: yes
      register: systemd
      ignore_errors: true
      notify:
        - Reload systemd
        - "Restart fact-backend"

    - name: Install systemd fact-frontend configuration
      ansible.builtin.template:
        src: "systemd-fact-frontend.service.j2"
        dest: "/lib/systemd/system/fact-frontend.service"
        mode: '0644'
        backup: yes
      register: systemd
      ignore_errors: true
      notify:
        - Reload systemd
        - "Restart fact-frontend"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start fact systemd service
  ansible.builtin.service:
    name: "fact-{{ item }}"
    enabled: "{{ fact_svc_enable | default(true) }}"
    state: "{{ fact_svc_state | default('started') }}"
  with_items:
    - db
    - backend
    - frontend
  notify:
    - Pause
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker")
        )

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
