---
name: default-HEAD-kitchen

on:
  push:
  pull_request:
  schedule:  # run weekly, every Tuesday 04:00
    - cron: '0 4 * * 2'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - distribution: fedora
            version: 37
            version2: 37
            suite: default-HEAD
            experimental: true
          - distribution: fedora
            version: 36
            version2: 36
            suite: default-HEAD
            experimental: true
          - distribution: ubuntu
            version: '22.04'
            version2: 2204
            suite: default-HEAD
            experimental: false
          - distribution: ubuntu
            version: '20.04'
            version2: 2004
            suite: default-HEAD
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      # ANSIBLE_EXTRA_FLAGS: "-e fact_nginx_shim=true -e fact_version=HEAD"

    steps:
      - uses: actions/checkout@v5
        with:
          path: juju4.fact
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.fact
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          [ -f molecule/default/requirements.yml ] && ansible-galaxy install -r molecule/default/requirements.yml
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
          { echo '[facthosts]'; echo 'localhost'; } >> inventory
          cat inventory
          sed -ri 's/hosts: facthosts/hosts: all/' molecule/default/verify.yml
      - name: Environment
        run: |
          pwd
          env
          find -ls
          df -h
      - name: Free disk space
        run: |
          sudo rm -Rf /usr/local/lib/android
          df -h
      - name: Mongodb - Disable Transparent Huge Pages (THP)
        run: |
          cat /sys/kernel/mm/transparent_hugepage/enabled
          echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
          cat /sys/kernel/mm/transparent_hugepage/enabled
      - name: Install lxd requirements
        run: |
          sudo apt-get update -qq
          sudo apt-get -y install lxd acl dnsmasq-base zfsutils-linux -q
          whoami
          grep lxd /etc/group
          echo "# remote list"
          lxc remote list
          echo "# image list"
          sudo lxc image list
          echo "# download image"
          [ ${{ matrix.distribution }} == ubuntu ] || sudo lxc image copy images:${{ matrix.distribution }}/${{ matrix.version }}/amd64 local: --alias=${{ matrix.distribution }}-${{ matrix.version }}-nossh || true
          [ ${{ matrix.distribution }} == ubuntu ] && sudo lxc image copy ubuntu:${{ matrix.version }} local: --alias=${{ matrix.distribution }}-${{ matrix.version }} || true
          echo "# image list"
          sudo lxc image list
          ## configure network
          ifconfig -a || true
          ip addr || true
          sudo lxc info
          sudo lxc network list
          sudo lxc network create lxdbr0
          sudo lxc network show lxdbr0
          sudo lxc network attach-profile lxdbr0 default ens4
          sudo lxc profile device get default ens4 nictype || true
          sudo service lxd restart || true
          ps ax | grep dnsmasq
          systemctl status -l --no-pager lxd || true
          cat /etc/network/interfaces.d/50-cloud-init.cfg || true
          sudo lxc network list
          # configure storage pool
          sudo lxc storage list
          sudo lxc storage create pool1 zfs size=45GB
          sudo lxc storage list
          sudo zpool list
          sudo lxc profile device add default root disk path=/ pool=pool1
          sudo lxc profile show default
          [ "X${{ matrix.distribution }}" == "Xcentos" -o "X${{ matrix.distribution }}" == "Xfedora" ] && cd $GITHUB_WORKSPACE/juju4.fact && sudo sh -x ./test/lxd/centos-ssh-image.sh ${{ matrix.version }} || true
      - name: Install kitchen requirements
        run: |
          sudo gem install test-kitchen --version "=1.25.0"
          sudo gem install kitchen-ansible
          sudo gem install kitchen-sync
          sudo gem install kitchen-lxd_cli
          sudo apt-get install -y libsodium23
          sudo gem install rbnacl --version 4.0.2
          sudo gem install bcrypt_pbkdf rbnacl-libsodium
          sudo -H ssh-keygen -t ed25519 -f /root/.ssh/id_rsa -P ""
          sudo ls -lA /root/.ssh/
          cd $GITHUB_WORKSPACE/juju4.fact && sudo kitchen diagnose --all
      # https://github.com/actionshub/test-kitchen
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Kitchen Converge
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact && sudo kitchen converge ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -l debug
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: $GITHUB_WORKSPACE/juju4.fact/.kitchen.yml
          TERM: xterm-256color
      - name: Kitchen Verify
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact && sudo kitchen verify ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }}
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: $GITHUB_WORKSPACE/juju4.fact/.kitchen.yml
          TERM: xterm-256color

      - name: On failure
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager status' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager --failed' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ls -l /usr/bin/ | egrep "(python|pip|ansible)"' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'pip freeze' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'pip3 freeze' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ip addr' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /etc/resolv.conf' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'host www.google.com' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ping -c 1 www.google.com' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ping -c 1 8.8.8.8' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ps auxw' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'curl -v https://luarocks.org/' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ls -lA /tmp/kitchen/' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /tmp/kitchen/hosts' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /etc/passwd' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'df -h' || true
          df -h
          sudo lxc storage list
          sudo zpool list
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - ansible setup
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ansible -i inventory --connection=local -m setup localhost' || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager status fact-backend' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager status fact-db' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager status fact-frontend' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager status mongodb' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager status nginx' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'systemctl -l --no-pager status docker' || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - journalctl
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'journalctl -xe --no-pager' || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - files
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ls -lR /var/_fact/FACT_core/'
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ls -lR /var/_fact/FACT_core/src/config'
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - config
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/_fact/FACT_core/src/config/main.cfg'
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/_fact/FACT_core/src/config/mongod.conf'
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - logs
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          set -x
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/log/fact/fact_main.log' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/log/fact/fact_main_frontend.log' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/log/fact/fact_main_backend.log' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/log/fact/fact_main_database.log' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/log/fact/fact_web.log' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/log/fact/fact_mongo.log' || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - nginx
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'find /etc/nginx -type f -ls'
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ls -la /etc/nginx/nginx.conf'
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /etc/nginx/nginx.conf'
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'nginx -V'
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'nginx -t'
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - curl
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          set -x
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'curl -kv https://localhost' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'curl -kv http://localhost:5000' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'curl -kv http://localhost:27018' || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - clamav
        run: |
          cd $GITHUB_WORKSPACE/juju4.fact
          set -x
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'ls -lA /var/lib/clamav/' || true
          sudo kitchen exec ${{ matrix.suite }}-${{ matrix.distribution }}-${{ matrix.version2 }} -c 'cat /var/log/clamav/freshclam.log' || true
        if: ${{ always() }}
        continue-on-error: true
